### PR TITLE
Add dominant sections strategy

### PR DESCRIPTION
**Pull request by misterbyrne**
I need to be able to detect the dominant direction of a bidirectional string which contains mostly one direction, but some small sections of other scripts (e.g. a document with quotes taken from different scripts). The strings I'm using can be very large and are mainly in a single script, so I've used an approach optimised for that.

- Added methods for the regexes of the characters strategy so the subclasses can access them
- Memoized the regexes for the characters strategy to improve performance
- Added a dominant sections strategy to allow for bidirectional strings which are mostly in a single script
- Improved the performance and memory usage of the ltr character detection (by using a single regex without any gsub)

### CODE REVIEW

**Comment by waiting-for-dev** [comment]
Hi,

thanks for your pull request. I'll check it as soon as possible. This week is specially complicated, but next week for sure I'll have the time.

Cheers

**Comment by waiting-for-dev** [comment]
Ok, finally I have a bit of time :)

> Added protected methods for the regexes of the characters strategy so the subclasses can access them

I like the refactor about encapsulating the regexes in their own method, but I would not make them `protected`. With `private` is enough to be called by its descendants, and `protected` is rarely used in ruby (mainly for operators).

> Added a dominant sections strategy to allow for bidirectional strings which are mostly in a single script

I'm not sure if the use case for this strategy is too specific. I mean, if you have a string which, in fact, is `bidi`, shouldn't you try to detect which part is `ltr` and which is `rtl`, and render them accordingly? Maybe I'm missing something.

> Improved the performance and memory usage of the ltr character detection (by using a single regex without any gsub)

Great!

**Comment by misterbyrne** [comment]
Thanks for reviewing this! Fair point about `protected` - I'll push a fix.

I should explain our use-case for detecting a dominant direction.

We have user generated content which we need to display in a block element in a web app (e.g. a `<div>`). We have no control over this content so it can contain anything.

We can specify the direction of the content of the element by using the [`dir` attribute](https://www.w3.org/TR/html4/struct/dirlang.html).

As per the spec, even with bidirectional content you must specify a direction for this attribute - either `ltr` or `rtl`.  There is some support for a third value, [`auto`](https://www.w3.org/International/questions/qa-html-dir#dirauto), but that only sets the direction based on the _first_ strongly directional character in the content (e.g. it will skip any whitespace, numerals, punctuation, etc.)

Here's a (very simplified and contrived) example (I took the text from [here](https://www.localisation.ie/oldwebsite/resources/lfresearch/Vol11_1HossariCater.pdf))...
```ruby
string = "Apple هي شركة أمريكية متعددة الجنسيات"
StringDirection::DominantSectionsStrategy.new.run(string)
=> "rtl"
```
...and example of how that might be rendered, in [jsfiddle](https://jsfiddle.net/rmpy6jjr/1/) with the `dir='auto'` attribute not doing a good job of displaying the content as intended.

Though, I will admit that I know nothing about RTL languages and how to use them!

**Comment by misterbyrne** [comment]
By the way, I've pushed a couple more commits, driven by the simple benchmark below.
The memoization was around 80 times faster for the `:characters` strategy (and the `:dominant_sections` one too).
The change to an iterative approach for the dominant sections strategy is about 1.6 times faster.

```ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'string-direction'
require 'pry'
require 'benchmark'

s = 'Englishعربية'
n = 10000
characters = StringDirection::Detector.new(:characters)
marks = StringDirection::Detector.new(:marks)
dominant = StringDirection::Detector.new(:dominant_sections)

Benchmark.bm do |x|
  x.report("characters:") { n.times do characters.direction(s); end }
  x.report("marks:     ") { n.times do marks.direction(s); end }
  x.report("dominant:  ") { n.times do dominant.direction(s); end }
end
```

**Comment by waiting-for-dev** [comment]
Hey! Thanks a lot for your work.

Ok, I see. This strategy can be very useful at practice. I guess the ideal would be to analyze the content and [tightly wrap opposite-direction phrases](https://www.w3.org/International/articles/inline-bidi-markup/#unknownuc), but I see that keeping simplicity and saving performance with an approximation are also valuable arguments.

But, just to be sure I understand it, in your comments it seems that you are trying to detect sections, meaning that `العَرَبِيةالعَرَبِيةالعَرَبِي the the` would be `ltr` because there are two `ltr` sections but only one `rtl` section. But in your code, and reflected in the very complete specs you have made, I think you are just counting characters, meaning that string would be `rtl` because it has more `rtl` characters. So I guess you changed your mind and forgot to update the comments.

I really like your algorithmic programming style. I love this academic scent :D But it is also a little bit difficult to understand at first sight. I have pushed another version (https://github.com/waiting-for-dev/string-direction/commit/d99520a649257bdd5716067b44a7138d82e47454) using a more declarative style with ruby built-in `scan` method. It really is much simpler to understand and, therefore, to maintain. Furthermore, even if with short string your version was more or less 1.5 faster, it is the opposite and with a much larger difference for long strings: (`run_declarative` is the version I have pushed):

    $LOAD_PATH.unshift File.expand_path('../lib/', __FILE__)
    require 'string-direction'
    require 'benchmark'

    string ="EnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربيةEnglishعربية"

    strategy = StringDirection::DominantSectionsStrategy.new

    [10, 100, 1000, 10000, 100000].each do |n|
      Benchmark.bm do |x|
        x.report("run #{n}:") { n.times do strategy.run(string); end }
        x.report("run_declarative #{n}:     ") { n.times do strategy.run_declarative(string); end }
      end
      puts '--------------------------------------------------------------------------------------------'
    end




    user     system      total        real
    run 10:  0.010000   0.000000   0.010000 (  0.006933)
    run_declarative 10:       0.000000   0.000000   0.000000 (  0.003255)
    --------------------------------------------------------------------------------------------
    user     system      total        real
    run 100:  0.070000   0.000000   0.070000 (  0.066368)
    run_declarative 100:       0.020000   0.000000   0.020000 (  0.025121)
    --------------------------------------------------------------------------------------------
    user     system      total        real
    run 1000:  0.650000   0.000000   0.650000 (  0.643740)
    run_declarative 1000:       0.230000   0.000000   0.230000 (  0.229848)
    --------------------------------------------------------------------------------------------
    user     system      total        real
    run 10000:  6.440000   0.000000   6.440000 (  6.443397)
    run_declarative 10000:       2.240000   0.000000   2.240000 (  2.244387)
    --------------------------------------------------------------------------------------------
     user     system      total        real
    run 100000: 65.070000   0.000000  65.070000 ( 65.067110)
    run_declarative 100000:      22.370000   0.000000  22.370000 ( 22.372259)
    --------------------------------------------------------------------------------------------

Please, give me your feedback and I will merge it to master.

Thanks

**Comment by misterbyrne** [comment]
Hey! Thanks 😄

You are correct, I was not trying to count the number of sections, but was counting characters, and was only breaking the string into sections as an optimisation for long strings! By trying to prevent any new strings being allocated (to keep RAM usage down), and by keeping the CPU within the C code of Ruby's Regexp implementation as much as possible. For a 1.5MB string, the imperative version is nearly 12 times faster... although my tests are with a long string which is mostly in one script (which is representative of the data that I'm using in real like), whereas your benchmark is with a string which is roughly 50% each script.

Although, I totally agree that something simpler like using `.scan` is waaayyy more readable and easier to understand. Readability is super-important!

A middle-ground, if you want to stick with the `.scan` method, would be to do something to avoid doubling up on RAM, e.g.

```ruby
ltr_characters = 0
string.scan(ltr_regex) { ltr_characters += 1}
```

It's performs similarly from a CPU usage point-of-view to `string.scan(ltr_regex).size` but doesn't allocate a big array.

**Comment by misterbyrne** [comment]
Oh, and I thought of another optimisation that could be added to the scan approach that is in the imperative approach. If a string has no RTL characters and even one LTR then we can stop scanning. And vice versa. A readable way to implement that would be to use the characters strategy first and only continue on to the dominant characters strategy of the characters strategy returns `bidi`. That would need benchmarking though!

**Comment by waiting-for-dev** [comment]
Great! It is much better your `scan` use, without having to call `size` in the generated array. I have updated it and I have already merged it to master.

Two considerations:

- Surely you are right and it would be more optimized to call `characters` strategy prior to begin scanning, but for now I prefer to leave it as is. Even if I don't like having a strategy descending from another strategy, I see this is useful. But I prefer not having to call `super` until there is really an use case when we see that optimization would be beneficial. Well, I want to stay away from premature optimization :)

- I have renamed `DominantSectionsStrategy` to `DominantStrategy`, because finally we are not talking about sections but characters.

If you are fetching it from rubygems, I have pushed version `1.1.1` with these changes.

Thanks a lot for your collaboration!

**Pull request merged**
