### PR TITLE
Refactor + Fix reamining RuboCop issues

### LINKED ISSUE #4: Dropping `git` in gemspec & using Packaging extension
Hi @waiting-for-dev 👋🏻 

Thanks for your great work!
However, whilst maintaining this in Debian, I found some issues that could be fixed by the `Packaging` extension of RuboCop. Would you be interested in doing so?

One specific issue that I'd like to resolve is dropping `git` in the gemspec file.
I'll be happy to raise a PR if you concur with this :)

### PR DESCRIPTION
**Pull request by utkarsh2102**
Hi @waiting-for-dev,

This fixes the remaining issues (from `.rubocop_todo.yml`) which had issues that needed some deeper look than the others!
All tests are passing and this is good to go now! 🎉 

Lastly, there are only 2 very small things left - one of which looks like a false positive of RuboCop so I've left it for now. They are small issues and can we worked upon later! 😄 

With all these things, this library looks pretty good now and completely fixes #4.
Thanks for all your amazing work on this! 🔥 ❤️ 

Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>

### CODE REVIEW

**Comment by waiting-for-dev** [comment]
Thanks again @utkarsh2102 ! I really appreciate your work on this :+1: 

Do you need all of this to be wrapped within another gem release?

**Comment by utkarsh2102** [comment]
Thanks, @waiting-for-dev, for your support so far!
I've just opened another PR (#8) to completely fix everything so there are no TODOs anymore 🎉 

Maybe you could do a patch release after this? It's not a necessity though, but it's good to have a release with everything now updated I think! But it's your call, really 😄

**Comment by utkarsh2102** [comment]
Additionally, I also would like to drop `git ls-files` and use the `Packaging` extension in devise-jwt, warden-jwt_auth (at least) and if you're interested, then web_pipe and front_matter_parser as well! 🙈 
You don't need to make a release for these^, just fixing them for now should suffice and help us in downstream maintenance I think! 😄 

Please let me know what you think?

**Comment by waiting-for-dev** [comment]
Yeah, of course, I'm more than happy to make life easier for downstream maintainers :slightly_smiling_face:

**Comment by utkarsh2102** [comment]
That is awesome, thanks again! 🚀 
I'll try to make some time and open PRs for these as well (or maybe if time permits, you can do too?)

Also, you still need to go activate the CI for this repository from your Travis CI account 🙈

**Pull request merged**
